# Module 1 - Exercise 1: Environment & Basics

## Learning Objectives
- Set up and verify PyTorch environment
- Master tensor creation methods and basic properties
- Understand tensor device management and CUDA availability
- Practice tensor indexing, slicing, and reshaping operations
- Convert between PyTorch tensors and NumPy arrays
- Explore tensor data types and memory layout

## Setup and Test Repository

First, let's clone the test repository and set up our environment for step-by-step validation with improved testing.

In [3]:
# Clone the test repository
!git clone https://github.com/racousin/data_science_practice.git /tmp/tests 2>/dev/null || true

# Import required modules
import sys
sys.path.append('/tmp/tests/tests/python_deep_learning')

# Import the improved test utilities
from test_utils import NotebookTestRunner, create_inline_test
from module1.test_exercise1 import Exercise1Validator, EXERCISE1_SECTIONS

# Create test runner and validator
test_runner = NotebookTestRunner("module1", 1)
validator = Exercise1Validator()

print("✅ Test framework loaded successfully!")
print("You can now run tests for each section as you complete them.")

✅ Test framework loaded successfully!
You can now run tests for each section as you complete them.


## Environment Setup

Let's import PyTorch and verify our installation, including CUDA availability.

In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt

# Print PyTorch version and setup information
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")
    print(f"Number of CUDA devices: {torch.cuda.device_count()}")
    print(f"Current CUDA device: {torch.cuda.current_device()}")
    print(f"Device name: {torch.cuda.get_device_name(0)}")

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)

PyTorch version: 2.8.0+cu126
CUDA available: True
CUDA version: 12.6
Number of CUDA devices: 1
Current CUDA device: 0
Device name: Tesla T4


## Section 1: Tensor Creation

Learn different methods to create PyTorch tensors with specific properties.

In [6]:
# TODO: Create a 3x3 tensor filled with zeros
tensor_zeros = torch.zeros(3,3)

# TODO: Create a 2x4 tensor filled with ones
tensor_ones = torch.ones(2,4)

# TODO: Create a 3x3 identity matrix
tensor_identity = torch.eye(3)

# TODO: Create a tensor with random values between 0 and 1, shape (2, 3, 4)
tensor_random = torch.rand(2,3,4)

# TODO: Create a tensor from a Python list [[1, 2, 3], [4, 5, 6]]
tensor_from_list = torch.tensor([[1, 2, 3], [4, 5, 6]])

# TODO: Create a tensor with values from 0 to 9
tensor_range = torch.arange(0,10)

# Display your created tensors
print("Your tensors:")
print(f"tensor_zeros:\n{tensor_zeros}")
print(f"tensor_ones:\n{tensor_ones}")
print(f"tensor_identity:\n{tensor_identity}")
print(f"tensor_random shape: {tensor_random.shape if tensor_random is not None else 'None'}")
print(f"tensor_from_list:\n{tensor_from_list}")
print(f"tensor_range: {tensor_range}")

Your tensors:
tensor_zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor_ones:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor_identity:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor_random shape: torch.Size([2, 3, 4])
tensor_from_list:
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor_range: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
# Test Section 1: Tensor Creation
section_tests = [(getattr(validator, name), desc) for name, desc in EXERCISE1_SECTIONS["Section 1: Tensor Creation"]]
test_runner.test_section("Section 1: Tensor Creation", validator, section_tests, locals())


Testing: Section 1: Tensor Creation
✅ Create 3x3 tensor of zeros
✅ Create 2x4 tensor of ones
✅ Create 3x3 identity matrix
✅ Create random tensor (2,3,4)
✅ Create tensor from list
✅ Create tensor with range 0-9

✅ Section 1: Tensor Creation - All tests passed!


True

## Section 2: Device Management

Understand how to work with different devices (CPU/CUDA) and move tensors between them.

In [8]:
# Create tensors on different devices
cpu_tensor = torch.randn(2, 3)
print(f"CPU tensor device: {cpu_tensor.device}")

# Check if CUDA is available and create GPU tensor if possible
if torch.cuda.is_available():
    gpu_tensor = torch.randn(2, 3, device='cuda')
    print(f"GPU tensor device: {gpu_tensor.device}")

    # Move CPU tensor to GPU
    cpu_to_gpu = cpu_tensor.to('cuda')
    print(f"Moved to GPU: {cpu_to_gpu.device}")

    # Move GPU tensor back to CPU
    gpu_to_cpu = gpu_tensor.cpu()
    print(f"Moved to CPU: {gpu_to_cpu.device}")
else:
    print("CUDA not available - all tensors will be on CPU")

# Verify same device operations
a = torch.ones(2, 3)
b = torch.ones(2, 3)
result = a + b  # Both on same device (CPU)
print(f"Addition result shape: {result.shape}, device: {result.device}")

CPU tensor device: cpu
GPU tensor device: cuda:0
Moved to GPU: cuda:0
Moved to CPU: cpu
Addition result shape: torch.Size([2, 3]), device: cpu


## Section 3: Tensor Attributes

Explore tensor properties and metadata information.

In [21]:
# Create a sample tensor for analysis
sample_tensor = torch.randn(3, 4, 5)

# TODO: Get the shape of the tensor
tensor_shape = sample_tensor.shape

# TODO: Get the data type of the tensor
tensor_dtype = sample_tensor.dtype

# TODO: Get the device the tensor is stored on
tensor_device = sample_tensor.device

# TODO: Get the number of dimensions
tensor_ndim = sample_tensor.ndim

# TODO: Get the total number of elements
tensor_numel = sample_tensor.numel()

# Display the attributes
print(f"Sample tensor shape: {tensor_shape}")
print(f"Data type: {tensor_dtype}")
print(f"Device: {tensor_device}")
print(f"Number of dimensions: {tensor_ndim}")
print(f"Total elements: {tensor_numel}")
print(f"Memory size (bytes): {sample_tensor.element_size() * sample_tensor.numel()}")
print(f"Stride: {sample_tensor.stride()}")

Sample tensor shape: torch.Size([3, 4, 5])
Data type: torch.float32
Device: cpu
Number of dimensions: 3
Total elements: 60
Memory size (bytes): 240
Stride: (20, 5, 1)


In [22]:
# Test Section 3: Tensor Attributes
section_tests = [(getattr(validator, name), desc) for name, desc in EXERCISE1_SECTIONS["Section 3: Tensor Attributes"]]
test_runner.test_section("Section 3: Tensor Attributes", validator, section_tests, locals())


Testing: Section 3: Tensor Attributes
✅ Get tensor shape
✅ Get tensor dtype
✅ Get tensor device
✅ Get tensor dimensions
✅ Get number of elements

✅ Section 3: Tensor Attributes - All tests passed!


True

## Section 4: Tensor Indexing and Slicing

Master accessing and modifying tensor elements using indexing and slicing.

In [50]:
# Create a sample tensor for indexing practice
tensor = torch.arange(24).reshape(4, 6)
print("Original tensor:")
print(tensor)
print(f"Shape: {tensor.shape}")

# TODO: Get the element at position (1, 3)
element = tensor[1,3]

# TODO: Get the second row (index 1)
second_row = tensor[1]

# TODO: Get the last column
last_column = tensor[:,-1]

# TODO: Get a 2x2 submatrix from the top-left corner
submatrix = tensor[0:2,0:2]

# TODO: Get every other element from the first row
alternating_elements = tensor[0,::2]

# Display your results
print(f"\nElement at (1,3): {element}")
print(f"Second row: {second_row}")
print(f"Last column: {last_column}")
print(f"Top-left 2x2 submatrix:\n{submatrix}")
print(f"Every other element from first row: {alternating_elements}")

Original tensor:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
Shape: torch.Size([4, 6])

Element at (1,3): 9
Second row: tensor([ 6,  7,  8,  9, 10, 11])
Last column: tensor([ 5, 11, 17, 23])
Top-left 2x2 submatrix:
tensor([[0, 1],
        [6, 7]])
Every other element from first row: tensor([0, 2, 4])


In [51]:
# Test Section 4: Indexing and Slicing
section_tests = [(getattr(validator, name), desc) for name, desc in EXERCISE1_SECTIONS["Section 4: Indexing and Slicing"]]
test_runner.test_section("Section 4: Indexing and Slicing", validator, section_tests, locals())


Testing: Section 4: Indexing and Slicing
✅ Access element at (1,3)
✅ Get second row
✅ Get last column
✅ Get 2x2 submatrix
✅ Get alternating elements

✅ Section 4: Indexing and Slicing - All tests passed!


True

## Section 5: Tensor Reshaping and Dimension Manipulation

Learn to manipulate tensor dimensions and understand memory layout.

In [56]:
# Create original tensor for reshaping
original = torch.arange(12)
print(f"Original tensor: {original}")
print(f"Original shape: {original.shape}")

# TODO: Reshape to 3x4
reshaped_3x4 = original.reshape(3,4)

# TODO: Reshape to 2x2x3
reshaped_2x2x3 = original.reshape(2,2,3)

# TODO: Flatten the 2x2x3 tensor back to 1D
flattened = reshaped_2x2x3.flatten()

# TODO: Add a new dimension at position 0 (unsqueeze)
unsqueezed = flattened.unsqueeze(0)

# TODO: Remove single-dimensional entries (squeeze)
tensor_with_singles = torch.randn(1, 3, 1, 4)
print(f"\nTensor with single dimensions: shape {tensor_with_singles.shape}")
squeezed = torch.squeeze(tensor_with_singles)

# Display your reshaped tensors
print(f"\nReshaped 3x4:\n{reshaped_3x4}")
print(f"Shape: {reshaped_3x4.shape if reshaped_3x4 is not None else 'None'}")

print(f"\nReshaped 2x2x3:\n{reshaped_2x2x3}")
print(f"Shape: {reshaped_2x2x3.shape if reshaped_2x2x3 is not None else 'None'}")

print(f"\nFlattened: {flattened}")
print(f"Shape: {flattened.shape if flattened is not None else 'None'}")

print(f"\nUnsqueezed: {unsqueezed}")
print(f"Shape: {unsqueezed.shape if unsqueezed is not None else 'None'}")

print(f"\nSqueezed shape: {squeezed.shape if squeezed is not None else 'None'}")

Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])

Tensor with single dimensions: shape torch.Size([1, 3, 1, 4])

Reshaped 3x4:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape: torch.Size([3, 4])

Reshaped 2x2x3:
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
Shape: torch.Size([2, 2, 3])

Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])

Unsqueezed: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])
Shape: torch.Size([1, 12])

Squeezed shape: torch.Size([3, 4])


In [57]:
# Test Section 5: Tensor Reshaping
section_tests = [(getattr(validator, name), desc) for name, desc in EXERCISE1_SECTIONS["Section 5: Tensor Reshaping"]]
test_runner.test_section("Section 5: Tensor Reshaping", validator, section_tests, locals())


Testing: Section 5: Tensor Reshaping
✅ Reshape to 3x4
✅ Reshape to 2x2x3
✅ Flatten tensor
✅ Add dimension with unsqueeze
✅ Remove single dimensions

✅ Section 5: Tensor Reshaping - All tests passed!


True

## Section 6: Tensor Data Types

Work with different tensor data types and learn about type conversions.

In [104]:
# TODO: Create a float32 tensor
float32_tensor = torch.tensor([1.,5.],dtype=torch.float32)

# TODO: Convert it to float64 (double precision)
float64_tensor = float32_tensor.to(torch.float64)

# TODO: Create an integer tensor and convert to float
int_tensor = torch.tensor([5,7],dtype = torch.int8)
int_to_float = int_tensor.to(float)

# TODO: Create a boolean tensor from a condition
comparison_tensor = torch.tensor([1, 2, 3, 4, 5])
bool_tensor = comparison_tensor > 3

# Display data types and their properties
print("Data Type Analysis:")
if float32_tensor is not None:
    print(f"float32_tensor dtype: {float32_tensor.dtype}, size: {float32_tensor.element_size()} bytes")
if float64_tensor is not None:
    print(f"float64_tensor dtype: {float64_tensor.dtype}, size: {float64_tensor.element_size()} bytes")
if int_tensor is not None:
    print(f"int_tensor dtype: {int_tensor.dtype}, size: {int_tensor.element_size()} bytes")
if int_to_float is not None:
    print(f"int_to_float dtype: {int_to_float.dtype}, size: {int_to_float.element_size()} bytes")
if bool_tensor is not None:
    print(f"bool_tensor: {bool_tensor}, dtype: {bool_tensor.dtype}")

# Demonstrate precision differences
if float32_tensor is not None and float64_tensor is not None:
    print(f"\nPrecision comparison:")
    print(f"float32: {float32_tensor}")
    print(f"float64: {float64_tensor}")

Data Type Analysis:
float32_tensor dtype: torch.float32, size: 4 bytes
float64_tensor dtype: torch.float64, size: 8 bytes
int_tensor dtype: torch.int8, size: 1 bytes
int_to_float dtype: torch.float64, size: 8 bytes
bool_tensor: tensor([False, False, False,  True,  True]), dtype: torch.bool

Precision comparison:
float32: tensor([1., 5.])
float64: tensor([1., 5.], dtype=torch.float64)


In [105]:
# Test Section 6: Data Types
section_tests = [(getattr(validator, name), desc) for name, desc in EXERCISE1_SECTIONS["Section 6: Data Types"]]
test_runner.test_section("Section 6: Data Types", validator, section_tests, locals())


Testing: Section 6: Data Types
✅ Create float32 tensor
✅ Convert to float64
❌ Convert int to float: int_tensor should have integer dtype, got torch.int8
✅ Create boolean tensor

❌ Section 6: Data Types - Some tests failed. Review the errors above.


False

## Section 7: NumPy Interoperability

Convert between PyTorch tensors and NumPy arrays, understanding memory sharing.

In [96]:
# TODO: Create a NumPy array and convert to tensor
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_numpy = torch.tensor(numpy_array)

# TODO: Create a tensor and convert to NumPy array
pytorch_tensor = torch.randn(2, 3)
numpy_from_tensor = np.array(pytorch_tensor)

# TODO: Demonstrate memory sharing between tensor and numpy array
shared_numpy = np.ones((2, 2))
shared_tensor = torch.from_numpy(shared_numpy)

# Display conversions
print("Conversion Results:")
print(f"Original NumPy array:\n{numpy_array}")
print(f"Tensor from NumPy: {tensor_from_numpy}")
print(f"Tensor from NumPy dtype: {tensor_from_numpy.dtype if tensor_from_numpy is not None else 'None'}")

print(f"\nOriginal PyTorch tensor: {pytorch_tensor}")
print(f"NumPy from tensor: {numpy_from_tensor}")

# Demonstrate memory sharing
if shared_tensor is not None:
    print(f"\nBefore modification:")
    print(f"NumPy array: {shared_numpy}")
    print(f"Shared tensor: {shared_tensor}")

    # Modify the numpy array
    shared_numpy[0, 0] = 999
    print(f"\nAfter modifying NumPy array:")
    print(f"NumPy array: {shared_numpy}")
    print(f"Shared tensor: {shared_tensor}")
    print("Notice how both arrays changed - they share memory!")

    # Reset for testing
    shared_numpy[0, 0] = 1

Conversion Results:
Original NumPy array:
[[1 2 3]
 [4 5 6]]
Tensor from NumPy: tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor from NumPy dtype: torch.int64

Original PyTorch tensor: tensor([[ 1.3415, -0.6912,  0.6742],
        [-0.5412, -0.2758,  0.2238]])
NumPy from tensor: [[ 1.3414553  -0.6912398   0.6742425 ]
 [-0.5411797  -0.27575162  0.22375408]]

Before modification:
NumPy array: [[1. 1.]
 [1. 1.]]
Shared tensor: tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

After modifying NumPy array:
NumPy array: [[999.   1.]
 [  1.   1.]]
Shared tensor: tensor([[999.,   1.],
        [  1.,   1.]], dtype=torch.float64)
Notice how both arrays changed - they share memory!


In [97]:
# Test Section 7: NumPy Interoperability
section_tests = [(getattr(validator, name), desc) for name, desc in EXERCISE1_SECTIONS["Section 7: NumPy Interoperability"]]
test_runner.test_section("Section 7: NumPy Interoperability", validator, section_tests, locals())


Testing: Section 7: NumPy Interoperability
✅ Convert NumPy to tensor
✅ Convert tensor to NumPy
✅ Test shared memory

✅ Section 7: NumPy Interoperability - All tests passed!


True

## Final Validation

Run the complete test suite summary to see your overall progress.

In [98]:
# Display final summary of all tests
test_runner.final_summary()


FINAL TEST SUMMARY
✅ Section 1: Tensor Creation: 6/6 tests passed
✅ Section 3: Tensor Attributes: 5/5 tests passed
✅ Section 4: Indexing and Slicing: 5/5 tests passed
✅ Section 5: Tensor Reshaping: 5/5 tests passed
❌ Section 6: Data Types: 3/4 tests passed
✅ Section 7: NumPy Interoperability: 3/3 tests passed
❌ Some tests are still failing. Please review and complete the TODOs.


False